title: "The wanderer mind"
description : "here I take on the journey of exploring difficult thoughts and their impact on our world"

remote_theme: ages-themes/time-machine@v0.2.0

plugins:
- jekyll-remote-theme # 

google_analytics: G-LLW8FL2LZW

github:
  repository_url : twitter.com
  owner_gravatar_url : facebook.com
